# PAKE System Kubernetes Secrets Configuration
# ============================================
#
# SECURITY NOTICE: This file contains NO hardcoded secrets.
# All secrets are managed through HashiCorp Vault integration.
#
# For production deployments:
# 1. Use External Secrets Operator to sync secrets from Vault
# 2. Configure Vault Agent for automatic secret injection
# 3. Never store real secrets in this file
#
# This file serves as a template showing the required secret structure.

apiVersion: v1
kind: Secret
metadata:
  name: pake-secrets
  namespace: pake-system
  labels:
    app.kubernetes.io/name: pake-secrets
    app.kubernetes.io/component: secrets
  annotations:
    config.kubernetes.io/warning: 'This is a template. Use External Secrets Operator or Vault Agent in production.'
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "pake-system"
type: Opaque
stringData:
  # Database Secrets - Retrieved from Vault
  DATABASE_PASSWORD: "REDACTED_SECRET"

  # Redis Secrets - Retrieved from Vault  
  REDIS_PASSWORD: "REDACTED_SECRET"

  # JWT Secrets - Retrieved from Vault
  JWT_SECRET_KEY: "REDACTED_SECRET"

  # API Keys - Retrieved from Vault
  FIRECRAWL_API_KEY: "REDACTED_SECRET"
  OPENAI_API_KEY: "REDACTED_SECRET"
  ANTHROPIC_API_KEY: "REDACTED_SECRET"

  # Application Secrets - Retrieved from Vault
  APP_SECRET_KEY: "REDACTED_SECRET"
---
# PostgreSQL Database Secret - Retrieved from Vault
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pake-system
  labels:
    app.kubernetes.io/name: postgres-secret
    app.kubernetes.io/component: database
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "pake-system"
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REDACTED_SECRET"
  POSTGRES_REPLICATION_PASSWORD: "REDACTED_SECRET"
---
# Redis Cache Secret - Retrieved from Vault
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: pake-system
  labels:
    app.kubernetes.io/name: redis-secret
    app.kubernetes.io/component: cache
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "pake-system"
type: Opaque
stringData:
  REDIS_PASSWORD: "REDACTED_SECRET"
