version: '3.8'

services:
  neo4j:
    image: neo4j:5.13
    environment:
      NEO4J_AUTH: neo4j/graphiti_REDACTED_SECRET
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data

  graphiti-mcp:
    image: zepai/knowledge-graph-mcp:latest
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MODEL_NAME: gpt-4o-mini
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: graphiti_REDACTED_SECRET
    ports:
      - '8000:8000'
    depends_on:
      - neo4j

volumes:
  neo4j_data:
