# Development Resource Limits - Reduced for local development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pake-backend
spec:
  template:
    spec:
      containers:
        - name: pake-backend
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '1Gi'
              cpu: '500m'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pake-frontend
spec:
  template:
    spec:
      containers:
        - name: pake-frontend
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '512Mi'
              cpu: '250m'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '1Gi'
              cpu: '500m'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              memory: '128Mi'
              cpu: '50m'
            limits:
              memory: '512Mi'
              cpu: '250m'
