apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pake-system-development

# Base configuration
resources:
- ../../base

# Development-specific labels

# Development-specific annotations
commonAnnotations:
  config.kubernetes.io/environment: development
  deployment.kubernetes.io/note: Development environment with debug features enabled

# Development images (use latest or specific dev tags)
images:
- name: pake-backend
  newName: pake-system/backend
  newTag: dev-latest
- name: pake-frontend
  newName: pake-system/frontend
  newTag: dev-latest

# Development configuration patches

# Development-specific ConfigMap patches
patches:
- path: dev-configmap-patch.yaml

# Development secrets patches

# Replicas for development (reduced)
replicas:
- count: 1
  name: pake-backend
- count: 1
  name: pake-frontend
- count: 1
  name: postgres
- count: 1
  name: redis

# Development namespace
namespace: pake-system
labels:
- includeSelectors: true
  pairs:
    environment: development
    tier: development
patches:
- path: dev-configmap-patch.yaml
- path: dev-secrets-patch.yaml
