{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "pake-api.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.externalSecrets.secretStore.kind }}
    name: {{ $.Values.externalSecrets.secretStore.name }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
---
{{- end }}
{{- end }}