apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pake-system-production

# Base configuration
resources:
- ../../base
- hpa.yaml
- vpa.yaml
- monitoring.yaml
- backup.yaml
- external-secrets.yaml

# Production-specific labels

# Production-specific annotations
commonAnnotations:
  backup.kubernetes.io/enabled: "true"
  config.kubernetes.io/environment: production
  deployment.kubernetes.io/note: Production environment with enterprise features
  monitoring.kubernetes.io/enabled: "true"

# Production images with specific stable tags
images:
- name: pake-backend
  newName: your-registry.com/pake-system/backend
  newTag: v1.0.0
- name: pake-frontend
  newName: your-registry.com/pake-system/frontend
  newTag: v1.0.0
- name: postgres
  newName: postgres
  newTag: 15-alpine
- name: redis
  newName: redis
  newTag: 7-alpine

# Production configuration patches

# Production-specific ConfigMap patches

# Production secrets - Use External Secrets Operator
# secretGenerator is commented out - use external-secrets.yaml instead
# secretGenerator:
#   - name: pake-secrets
#     behavior: replace
#     files:
#       - DATABASE_PASSWORD=secrets/postgres-REDACTED_SECRET
#       - REDIS_PASSWORD=secrets/redis-REDACTED_SECRET
#       - JWT_SECRET_KEY=secrets/jwt-secret

# Production replicas (high availability)
replicas:
- count: 3
  name: pake-backend
- count: 3
  name: pake-frontend
- count: 1
  name: postgres
- count: 3
  name: redis

# Production namespace
namespace: pake-system

# JSON patches for fine-grained production modifications
labels:
- includeSelectors: true
  pairs:
    environment: production
    tier: enterprise
patches:
- path: production-configmap-patch.yaml
- patch: |-
    - op: add
      path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-type
      value: nlb
    - op: add
      path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-backend-protocol
      value: tcp
  target:
    kind: Service
    name: pake-backend-service
    version: v1
- path: production-resources.yaml
- path: production-security.yaml
- path: production-storage.yaml
- path: production-replicas.yaml
