# PAKE System - Alertmanager Configuration
# Alert routing and notification management

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@your-domain.com'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing rules
route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'default'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Security alerts - immediate notification
    - match_re:
        alertname: '.*Security.*|.*Login.*|.*SSL.*'
      receiver: 'security-team'
      group_wait: 0s

    # Database alerts - DBA team
    - match_re:
        alertname: '.*PostgreSQL.*|.*Database.*'
      receiver: 'database-team'

    # Performance alerts - dev team
    - match:
        severity: warning
      receiver: 'performance-alerts'
      group_interval: 10m

# Inhibition rules - suppress alerts
inhibit_rules:
  # Suppress individual service alerts if the entire system is down
  - source_match:
      alertname: 'ServiceDown'
      service: 'pake-system'
    target_match:
      severity: 'warning'
    equal: ['instance']

  # Suppress memory alerts if the system is down
  - source_match:
      severity: 'critical'
    target_match:
      alertname: 'HighMemoryUsage'
    equal: ['instance']

# Notification receivers
receivers:
  # Default receiver
  - name: 'default'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#pake-alerts'
        title: 'PAKE System Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    slack_configs:
      - api_url: '${SLACK_CRITICAL_WEBHOOK_URL}'
        channel: '#pake-critical'
        title: '🚨 CRITICAL: PAKE System Alert'
        text: |
          @channel CRITICAL ALERT!
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Instance:* {{ .Labels.instance }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}
        send_resolved: true

    email_configs:
      - to: '${CRITICAL_EMAIL_LIST}'
        subject: '[CRITICAL] PAKE System Alert: {{ .GroupLabels.alertname }}'
        body: |
          Critical alert in PAKE System:

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Severity: {{ .Labels.severity }}
          Started: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

          Dashboard: https://grafana.your-domain.com
          Runbooks: https://docs.your-domain.com/runbooks

    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ .GroupLabels.alertname }} - {{ .CommonAnnotations.summary }}'

  # Security team notifications
  - name: 'security-team'
    email_configs:
      - to: 'security@your-domain.com'
        subject: '[SECURITY] PAKE System Security Alert'
        body: |
          Security alert detected in PAKE System:

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

    slack_configs:
      - api_url: '${SLACK_SECURITY_WEBHOOK_URL}'
        channel: '#security-alerts'
        title: '🔒 Security Alert: PAKE System'
        text: |
          Security incident detected!
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}

  # Database team notifications
  - name: 'database-team'
    email_configs:
      - to: 'dba@your-domain.com'
        subject: '[DATABASE] PAKE System Database Alert'
        body: |
          Database alert in PAKE System:

          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Instance: {{ .Labels.instance }}
          {{ end }}

    slack_configs:
      - api_url: '${SLACK_DBA_WEBHOOK_URL}'
        channel: '#database-alerts'
        title: '🗄️ Database Alert: PAKE System'

  # Performance alerts - development team
  - name: 'performance-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#pake-performance'
        title: '⚠️ Performance Alert: PAKE System'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}

  # Webhook notifications for integrations
  - name: 'webhook-notifications'
    webhook_configs:
      - url: '${WEBHOOK_URL}'
        send_resolved: true
        http_config:
          bearer_token: '${WEBHOOK_TOKEN}'
