# PAKE System - Alerting Rules
# Comprehensive alerts for system health and performance

groups:
  # Critical System Alerts
  - name: pake-system-critical
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'Service {{ $labels.job }} is down'
          description: 'Service {{ $labels.job }} on instance {{ $labels.instance }} has been down for more than 1 minute.'

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: 'High error rate detected'
          description: 'Error rate is {{ $value }} errors per second for service {{ $labels.job }}.'

      - alert: DatabaseConnectionFailure
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'PostgreSQL connection failure'
          description: 'Cannot connect to PostgreSQL database.'

      - alert: RedisConnectionFailure
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'Redis connection failure'
          description: 'Cannot connect to Redis cache.'

  # Performance Alerts
  - name: pake-performance
    rules:
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High response time detected'
          description: '95th percentile response time is {{ $value }}s for service {{ $labels.job }}.'

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High CPU usage'
          description: 'CPU usage is above 80% for instance {{ $labels.instance }}.'

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High memory usage'
          description: 'Memory usage is above 85% for instance {{ $labels.instance }}.'

      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High disk usage'
          description: 'Disk usage is above 85% for instance {{ $labels.instance }}.'

  # Application-Specific Alerts
  - name: pake-application
    rules:
      - alert: WebSocketConnectionFailure
        expr: probe_success{job="blackbox-websocket"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: 'WebSocket connection failure'
          description: 'WebSocket endpoint {{ $labels.instance }} is not accessible.'

      - alert: SearchLatencyHigh
        expr: histogram_quantile(0.95, rate(search_duration_seconds_bucket[10m])) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High search latency'
          description: '95th percentile search latency is {{ $value }}s.'

      - alert: CacheHitRateLow
        expr: rate(cache_hits_total[10m]) / rate(cache_requests_total[10m]) < 0.8
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: 'Low cache hit rate'
          description: 'Cache hit rate is {{ $value | humanizePercentage }} which is below 80%.'

      - alert: ActiveUsersDrop
        expr: websocket_connected_users < 5
        for: 10m
        labels:
          severity: info
        annotations:
          summary: 'Low number of active users'
          description: 'Only {{ $value }} users are currently connected via WebSocket.'

  # Database Alerts
  - name: pake-database
    rules:
      - alert: PostgreSQLTooManyConnections
        expr: sum(pg_stat_activity_count) by (instance) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: 'Too many PostgreSQL connections'
          description: 'PostgreSQL instance {{ $labels.instance }} has {{ $value }} active connections.'

      - alert: PostgreSQLSlowQuery
        expr: pg_stat_activity_max_tx_duration{state="active"} > 300
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: 'PostgreSQL slow query detected'
          description: 'Query running for {{ $value }}s on instance {{ $labels.instance }}.'

      - alert: PostgreSQLDeadlocks
        expr: rate(pg_stat_database_deadlocks[5m]) > 0.01
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: 'PostgreSQL deadlocks detected'
          description: 'Deadlock rate is {{ $value }} per second on database {{ $labels.datname }}.'

  # Security Alerts
  - name: pake-security
    rules:
      - alert: TooManyFailedLogins
        expr: rate(authentication_failures_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: 'Too many failed login attempts'
          description: '{{ $value }} failed login attempts per second detected.'

      - alert: SuspiciousAPIUsage
        expr: rate(http_requests_total{status="429"}[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'Suspicious API usage detected'
          description: 'High rate of rate-limited requests: {{ $value }} per second.'

      - alert: SSLCertificateExpiring
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: 'SSL certificate expiring soon'
          description: 'SSL certificate for {{ $labels.instance }} expires in {{ $value | humanizeDuration }}.'

  # Infrastructure Alerts
  - name: pake-infrastructure
    rules:
      - alert: ContainerRestart
        expr: increase(container_start_time_seconds[1h]) > 1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: 'Container restart detected'
          description: 'Container {{ $labels.name }} has restarted {{ $value }} times in the last hour.'

      - alert: ContainerHighMemory
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 90
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: 'Container high memory usage'
          description: 'Container {{ $labels.name }} memory usage is {{ $value }}%.'

      - alert: RedisMemoryHigh
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'Redis high memory usage'
          description: 'Redis memory usage is {{ $value }}% on instance {{ $labels.instance }}.'
