# PAKE System Prometheus Alerting Rules

groups:
  - name: pake-system.rules
    rules:
      # High error rate
      - alert: PAKESystemHighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
          service: pake-system
        annotations:
          summary: "PAKE System high error rate"
          description: "PAKE System is experiencing a high error rate of {{ $value }} errors per second for the last 5 minutes."

      # High response time
      - alert: PAKESystemHighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System high response time"
          description: "PAKE System 95th percentile response time is {{ $value }}s for the last 5 minutes."

      # High CPU usage
      - alert: PAKESystemHighCPUUsage
        expr: rate(container_cpu_usage_seconds_total{pod=~"pake-system-.*"}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System high CPU usage"
          description: "PAKE System pod {{ $labels.pod }} CPU usage is {{ $value }} for the last 5 minutes."

      # High memory usage
      - alert: PAKESystemHighMemoryUsage
        expr: container_memory_usage_bytes{pod=~"pake-system-.*"} / container_spec_memory_limit_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System high memory usage"
          description: "PAKE System pod {{ $labels.pod }} memory usage is {{ $value }} for the last 5 minutes."

      # Pod down
      - alert: PAKESystemPodDown
        expr: up{pod=~"pake-system-.*"} == 0
        for: 1m
        labels:
          severity: critical
          service: pake-system
        annotations:
          summary: "PAKE System pod down"
          description: "PAKE System pod {{ $labels.pod }} has been down for more than 1 minute."

      # Database connection issues
      - alert: PAKESystemDatabaseConnectionIssues
        expr: rate(database_connection_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: pake-system
        annotations:
          summary: "PAKE System database connection issues"
          description: "PAKE System is experiencing database connection errors at a rate of {{ $value }} per second."

      # Redis connection issues
      - alert: PAKESystemRedisConnectionIssues
        expr: rate(redis_connection_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System Redis connection issues"
          description: "PAKE System is experiencing Redis connection errors at a rate of {{ $value }} per second."

      # Low cache hit rate
      - alert: PAKESystemLowCacheHitRate
        expr: rate(redis_hits_total[5m]) / (rate(redis_hits_total[5m]) + rate(redis_misses_total[5m])) < 0.8
        for: 5m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System low cache hit rate"
          description: "PAKE System cache hit rate is {{ $value }} for the last 5 minutes."

      # High queue length
      - alert: PAKESystemHighQueueLength
        expr: celery_queue_length > 1000
        for: 5m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System high queue length"
          description: "PAKE System queue length is {{ $value }} for the last 5 minutes."

      # Failed jobs
      - alert: PAKESystemFailedJobs
        expr: rate(celery_tasks_failed_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: pake-system
        annotations:
          summary: "PAKE System failed jobs"
          description: "PAKE System is experiencing job failures at a rate of {{ $value }} per second."

  - name: pake-system.sla
    rules:
      # SLA breach - availability
      - alert: PAKESystemSLABreachAvailability
        expr: (up{pod=~"pake-system-.*"} == 0) and (time() - on() (up{pod=~"pake-system-.*"} == 0) > 300)
        for: 0m
        labels:
          severity: critical
          service: pake-system
          sla: availability
        annotations:
          summary: "PAKE System SLA breach - availability"
          description: "PAKE System has been down for more than 5 minutes, breaching SLA."

      # SLA breach - response time
      - alert: PAKESystemSLABreachResponseTime
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 10m
        labels:
          severity: critical
          service: pake-system
          sla: response-time
        annotations:
          summary: "PAKE System SLA breach - response time"
          description: "PAKE System 99th percentile response time is {{ $value }}s for the last 10 minutes, breaching SLA."

  - name: pake-system.capacity
    rules:
      # Disk space low
      - alert: PAKESystemDiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System disk space low"
          description: "PAKE System node {{ $labels.instance }} disk space is {{ $value }}% available."

      # High load average
      - alert: PAKESystemHighLoadAverage
        expr: node_load1 > 10
        for: 5m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System high load average"
          description: "PAKE System node {{ $labels.instance }} load average is {{ $value }}."

      # Network errors
      - alert: PAKESystemNetworkErrors
        expr: rate(node_network_receive_errs_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: pake-system
        annotations:
          summary: "PAKE System network errors"
          description: "PAKE System node {{ $labels.instance }} is experiencing network errors at a rate of {{ $value }} per second."
