apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-primary
  namespace: wealth-platform
  labels:
    app: postgresql
    component: database
    tier: data
    role: primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      role: primary
  template:
    metadata:
      labels:
        app: postgresql
        role: primary
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: REDACTED_SECRET
            - name: POSTGRES_REPLICATION_MODE
              value: master
            - name: POSTGRES_REPLICATION_USER
              value: replicator
            - name: POSTGRES_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: replication-REDACTED_SECRET
          ports:
            - containerPort: 5432
              name: postgresql
          resources:
            requests:
              cpu: '4'
              memory: '32Gi'
            limits:
              cpu: '8'
              memory: '64Gi'
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: postgresql-config
              mountPath: /etc/postgresql
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 -p 5432
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h 127.0.0.1 -p 5432
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data-pvc
        - name: postgresql-config
          configMap:
            name: postgresql-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-primary-service
  namespace: wealth-platform
  labels:
    app: postgresql
    role: primary
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: postgresql
    role: primary
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-pvc
  namespace: wealth-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti # 2TB for financial data
  storageClassName: fast-ssd
# Secret is now managed by External Secrets Operator
# See external-secrets-operator.yaml for configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: wealth-platform
data:
  postgresql.conf: |
    # Connection settings
    listen_addresses = '*'
    port = 5432
    max_connections = 500

    # Memory settings (optimized for 64GB RAM)
    shared_buffers = 16GB
    effective_cache_size = 48GB
    work_mem = 256MB
    maintenance_work_mem = 2GB

    # WAL settings
    wal_buffers = 64MB
    checkpoint_completion_target = 0.9
    wal_writer_delay = 200ms

    # Performance settings
    random_page_cost = 1.1  # SSD storage
    effective_io_concurrency = 200

    # Logging
    log_destination = 'stderr'
    logging_collector = on
    log_directory = '/var/log/postgresql'
    log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
    log_statement = 'ddl'
    log_min_duration_statement = 1000  # Log slow queries > 1s

    # Replication settings
    wal_level = replica
    max_wal_senders = 3
    wal_keep_size = 1GB
