apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wealth-platform-ingress
  namespace: wealth-platform
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '50m'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '300'
    nginx.ingress.kubernetes.io/rate-limit: '1000' # 1000 requests per minute
    nginx.ingress.kubernetes.io/rate-limit-window: '1m'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/whitelist-source-range: '10.0.0.0/8,192.168.0.0/16,172.16.0.0/12' # Internal access only
spec:
  tls:
    - hosts:
        - wealth.internal.domain.com
        - api.wealth.internal.domain.com
        - grafana.wealth.internal.domain.com
      secretName: wealth-platform-tls
  rules:
    - host: wealth.internal.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wealth-platform-service
                port:
                  number: 80
    - host: api.wealth.internal.domain.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: wealth-platform-service
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: wealth-platform-service
                port:
                  number: 80
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: wealth-platform-service
                port:
                  number: 80
    - host: grafana.wealth.internal.domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
  namespace: wealth-platform
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'nlb'
    service.beta.kubernetes.io/aws-load-balancer-scheme: 'internal'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
