apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: pake-system-staging

# Base configuration
resources:
- ../../base
- staging-monitoring.yaml

# Staging-specific labels

# Staging-specific annotations
commonAnnotations:
  config.kubernetes.io/environment: staging
  deployment.kubernetes.io/note: Staging environment for integration testing

# Staging images (use release candidates or stable dev tags)
images:
- name: pake-backend
  newName: your-registry.com/pake-system/backend
  newTag: v1.0.0-rc1
- name: pake-frontend
  newName: your-registry.com/pake-system/frontend
  newTag: v1.0.0-rc1

# Staging configuration patches

# Staging-specific ConfigMap and Secrets patches

# Staging replicas (production-like but reduced)
replicas:
- count: 2
  name: pake-backend
- count: 2
  name: pake-frontend
- count: 1
  name: postgres
- count: 1
  name: redis

# Staging namespace
namespace: pake-system
labels:
- includeSelectors: true
  pairs:
    environment: staging
    tier: staging
patches:
- path: staging-configmap-patch.yaml
- path: staging-secrets-patch.yaml
- path: staging-resources.yaml
