# Staging Secrets Patch
apiVersion: v1
kind: Secret
metadata:
  name: pake-secrets
  namespace: pake-system
type: Opaque
stringData:
  # Staging-specific secrets
  DATABASE_PASSWORD: 'staging-db-REDACTED_SECRET'
  REDIS_PASSWORD: 'staging-redis-REDACTED_SECRET'
  JWT_SECRET_KEY: 'staging-jwt-secret-key'
  FIRECRAWL_API_KEY: 'staging-firecrawl-key'
  OPENAI_API_KEY: 'staging-openai-key'
  ANTHROPIC_API_KEY: 'staging-anthropic-key'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pake-system
type: Opaque
stringData:
  POSTGRES_PASSWORD: 'staging-db-REDACTED_SECRET'
  POSTGRES_REPLICATION_PASSWORD: 'staging-replication-REDACTED_SECRET'
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: pake-system
type: Opaque
stringData:
  REDIS_PASSWORD: 'staging-redis-REDACTED_SECRET'
