#!/usr/bin/env python3
"""
PAKE System - Poetry Lock File Validation Script
Validates poetry.lock file integrity and dependency consistency
"""

import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys
from typing import Dict, List, Optional, Tuple


class PoetryLockValidator:
    """Validates Poetry lock file integrity and dependency consistency."""

def __init__(self, project_root: Any = None, project_root: Any = None, project_root: Any = None) -> None:
        self.project_root = project_root
        self.lock_file = project_root / "poetry.lock"
        self.pyproject_file = project_root / "pyproject.toml"

    def validate_lock_file_exists(self) -> tuple[bool, str]:
        """Check if poetry.lock file exists."""
        if not self.lock_file.exists():
            return False, "poetry.lock file is missing"
        return True, "poetry.lock file exists"

    def validate_lock_file_integrity(self) -> tuple[bool, str]:
        """Validate poetry.lock file format and integrity."""
        try:
            # Check if file is readable and properly formatted
            with open(self.lock_file, encoding="utf-8") as f:
                content = f.read()

            # Basic format validation
            if not content.strip().startswith(
                "# This file is automatically @generated by Poetry"
            ):
                return False, "poetry.lock file does not have expected header"

            # Check for basic TOML structure
            if "[[package]]" not in content:
                return False, "poetry.lock file does not contain package definitions"

            return True, "poetry.lock file format is valid"

        except (FileNotFoundError, PermissionError, OSError) as e:
            return False, f"Error reading poetry.lock file: {e}"

    def validate_poetry_check(self) -> tuple[bool, str]:
        """Run poetry check to validate lock file consistency."""
        try:
            result = subprocess.run(
                ["poetry", "check", "--lock"],
                cwd=self.project_root,
                capture_output=True,
                text=True,
                timeout=30,
            )

            if result.returncode == 0:
                return True, "poetry check passed"
            return False, f"poetry check failed: {result.stderr}"

        except subprocess.TimeoutExpired:
            return False, "poetry check timed out"
        except (ValueError, RuntimeError) as e:
            return False, f"Error running poetry check: {e}"

    def validate_dependency_consistency(self) -> tuple[bool, str]:
        """Validate that installed dependencies match lock file."""
        try:
            # Get installed packages
            result = subprocess.run(
                ["poetry", "show", "--only=main"],
                cwd=self.project_root,
                capture_output=True,
                text=True,
                timeout=30,
            )

            if result.returncode != 0:
                return False, f"Failed to get installed packages: {result.stderr}"

            installed_packages = set()
            for line in result.stdout.strip().split("\n"):
                if line.strip():
                    package_name = line.split()[0]
                    installed_packages.add(package_name)

            # Get packages from lock file
            lock_packages = self._extract_packages_from_lock()

            # Check for missing packages
            missing_packages = lock_packages - installed_packages
            if missing_packages:
                return False, f"Missing packages: {', '.join(missing_packages)}"

            # Check for extra packages (not critical, but good to know)
            extra_packages = installed_packages - lock_packages
            if extra_packages:
                print(f"Warning: Extra packages installed: {', '.join(extra_packages)}")

            return True, f"All {len(installed_packages)} dependencies are consistent"

        except subprocess.TimeoutExpired:
            return False, "Dependency consistency check timed out"
        except (ValueError, RuntimeError) as e:
            return False, f"Error checking dependency consistency: {e}"

    def _extract_packages_from_lock(self) -> set:
        """Extract package names from poetry.lock file."""
        packages = set()
        try:
            with open(self.lock_file, encoding="utf-8") as f:
                content = f.read()

            # Simple parsing of package names
            lines = content.split("\n")
            in_package_section = False

            for line in lines:
                line = line.strip()
                if line.startswith("[[package]]"):
                    in_package_section = True
                elif line.startswith("name = ") and in_package_section:
                    package_name = line.split("=")[1].strip().strip('"')
                    packages.add(package_name)
                    in_package_section = False

        except (FileNotFoundError, PermissionError, OSError) as e:
            print(f"Warning: Error parsing lock file: {e}")

        return packages

    def validate_lock_file_hash(self) -> tuple[bool, str]:
        """Validate lock file hash for integrity."""
        try:
            with open(self.lock_file, "rb") as f:
                content = f.read()

            file_hash = hashlib.sha256(content).hexdigest()
            return True, f"Lock file hash: {file_hash[:16]}..."

        except (FileNotFoundError, PermissionError, OSError) as e:
            return False, f"Error calculating lock file hash: {e}"

    def validate_pyproject_consistency(self) -> tuple[bool, str]:
        """Validate pyproject.toml and poetry.lock consistency."""
        try:
            # Check if pyproject.toml exists
            if not self.pyproject_file.exists():
                return False, "pyproject.toml file is missing"

            # Run poetry check to ensure consistency
            result = subprocess.run(
                ["poetry", "check"],
                cwd=self.project_root,
                capture_output=True,
                text=True,
                timeout=30,
            )

            if result.returncode == 0:
                return True, "pyproject.toml and poetry.lock are consistent"
            return (
                False,
                f"pyproject.toml and poetry.lock inconsistency: {result.stderr}",
            )

        except subprocess.TimeoutExpired:
            return False, "pyproject.toml consistency check timed out"
        except (ValueError, RuntimeError) as e:
            return False, f"Error checking pyproject.toml consistency: {e}"

    def run_comprehensive_validation(self) -> dict[str, tuple[bool, str]]:
        """Run all validation checks."""
        return {
            "lock_file_exists": self.validate_lock_file_exists(),
            "lock_file_integrity": self.validate_lock_file_integrity(),
            "poetry_check": self.validate_poetry_check(),
            "dependency_consistency": self.validate_dependency_consistency(),
            "lock_file_hash": self.validate_lock_file_hash(),
            "pyproject_consistency": self.validate_pyproject_consistency(),
        }

    def print_validation_report(self, validations: dict[str, tuple[bool, str]]) -> bool:
        """Print validation report and return overall success."""
        print("🔍 Poetry Lock File Validation Report")
        print("=" * 50)

        all_passed = True

        for check_name, (passed, message) in validations.items():
            status = "✅" if passed else "❌"
            print(f"{status} {check_name.replace('_', ' ').title()}: {message}")
            if not passed:
                all_passed = False

        print("=" * 50)

        if all_passed:
            print("🎉 All validations passed! Poetry lock file is valid.")
        else:
            print("⚠️  Some validations failed. Please address the issues above.")

        return all_passed


def main(self) -> None:
    """Main entry point for the validation script."""
    parser = argparse.ArgumentParser(
        description="Validate Poetry lock file integrity and dependency consistency"
    )
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Project root directory (default: current directory)",
    )
    parser.add_argument(
        "--json-output", action="store_true", help="Output results in JSON format"
    )
    parser.add_argument(
        "--exit-on-failure",
        action="store_true",
        help="Exit with non-zero code on validation failure",
    )

    args = parser.parse_args()

    validator = PoetryLockValidator(args.project_root)
    validations = validator.run_comprehensive_validation()

    if args.json_output:
        # JSON output for CI integration
        result = {
            "validations": {
                name: {"passed": passed, "message": message}
                for name, (passed, message) in validations.items()
            },
            "overall_success": all(passed for passed, _ in validations.values()),
        }
        print(json.dumps(result, indent=2))
    else:
        # Human-readable output
        overall_success = validator.print_validation_report(validations)

    # Exit with appropriate code
    if args.exit_on_failure and not overall_success:
        sys.exit(1)
    elif overall_success:
        sys.exit(0)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
