# This secret is now managed by External Secrets Operator
# See external-secrets-operator.yaml for configuration
#
# To create this secret manually for development:
# kubectl create secret generic pake-secrets \
#   --from-literal=DATABASE_PASSWORD="your-secure-REDACTED_SECRET" \
#   --from-literal=DATABASE_URL="postgresql://pake_user:your-secure-REDACTED_SECRET@postgres-service:5432/pake_system" \
#   --from-literal=REDIS_PASSWORD="your-secure-redis-REDACTED_SECRET" \
#   --from-literal=REDIS_URL="redis://:your-secure-redis-REDACTED_SECRET@redis-service:6379/0" \
#   --from-literal=JWT_SECRET_KEY="your-very-long-secure-random-string" \
#   --from-literal=FIRECRAWL_API_KEY="your-firecrawl-api-key" \
#   --from-literal=OPENAI_API_KEY="your-openai-api-key" \
#   --from-literal=EMAIL_HOST="smtp.gmail.com" \
#   --from-literal=EMAIL_PORT="587" \
#   --from-literal=EMAIL_USERNAME="your-email@gmail.com" \
#   --from-literal=EMAIL_PASSWORD="your-app-REDACTED_SECRET" \
#   -n pake-system
# PostgreSQL secret is now managed by External Secrets Operator
# See external-secrets-operator.yaml for configuration
#
# To create this secret manually for development:
# kubectl create secret generic postgres-secret \
#   --from-literal=POSTGRES_DB="pake_system" \
#   --from-literal=POSTGRES_USER="pake_user" \
#   --from-literal=POSTGRES_PASSWORD="your-secure-REDACTED_SECRET" \
#   -n pake-system

# Redis secret is now managed by External Secrets Operator
# See external-secrets-operator.yaml for configuration
#
# To create this secret manually for development:
# kubectl create secret generic redis-secret \
#   --from-literal=REDIS_PASSWORD="your-secure-redis-REDACTED_SECRET" \
#   -n pake-system
