apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pake-system.fullname" . }}-config
  labels:
    {{- include "pake-system.labels" . | nindent 4 }}
data:
  {{- range .Values.env }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
