apiVersion: v1
kind: Service
metadata:
  name: {{ include "pake-system.fullname" . }}
  labels:
    {{- include "pake-system.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pake-system.selectorLabels" . | nindent 4 }}
